<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Netasha K. Pizano">

<title>Partial and Semi Partial Correlations</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="Partial and Semi Partial Correlations_files/libs/clipboard/clipboard.min.js"></script>
<script src="Partial and Semi Partial Correlations_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Partial and Semi Partial Correlations_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Partial and Semi Partial Correlations_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Partial and Semi Partial Correlations_files/libs/quarto-html/popper.min.js"></script>
<script src="Partial and Semi Partial Correlations_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Partial and Semi Partial Correlations_files/libs/quarto-html/anchor.min.js"></script>
<link href="Partial and Semi Partial Correlations_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Partial and Semi Partial Correlations_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Partial and Semi Partial Correlations_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Partial and Semi Partial Correlations_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Partial and Semi Partial Correlations_files/libs/bootstrap/bootstrap-bc52bbd851521d97b8f64129895c69bb.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#define-partial-correlations-goal" id="toc-define-partial-correlations-goal" class="nav-link" data-scroll-target="#define-partial-correlations-goal">Define: Partial Correlations Goal</a>
  <ul class="collapse">
  <li><a href="#hypotheses" id="toc-hypotheses" class="nav-link" data-scroll-target="#hypotheses">Hypotheses</a></li>
  <li><a href="#assumptions-of-pearson-correlation" id="toc-assumptions-of-pearson-correlation" class="nav-link" data-scroll-target="#assumptions-of-pearson-correlation">Assumptions of Pearson Correlation</a></li>
  <li><a href="#technique-using-linear-model-regession-residuals" id="toc-technique-using-linear-model-regession-residuals" class="nav-link" data-scroll-target="#technique-using-linear-model-regession-residuals">Technique using Linear Model Regession Residuals</a></li>
  </ul></li>
  <li><a href="#example-partial-correlation-with-missing-data" id="toc-example-partial-correlation-with-missing-data" class="nav-link" data-scroll-target="#example-partial-correlation-with-missing-data">Example Partial Correlation with Missing Data</a>
  <ul class="collapse">
  <li><a href="#read-in-the-data" id="toc-read-in-the-data" class="nav-link" data-scroll-target="#read-in-the-data">Read in the data</a></li>
  <li><a href="#wrangle-the-data-descriptive-statistics" id="toc-wrangle-the-data-descriptive-statistics" class="nav-link" data-scroll-target="#wrangle-the-data-descriptive-statistics">Wrangle the data (descriptive statistics)</a></li>
  <li><a href="#use-visualizations-such-as-box-plots-to-identify-outliers" id="toc-use-visualizations-such-as-box-plots-to-identify-outliers" class="nav-link" data-scroll-target="#use-visualizations-such-as-box-plots-to-identify-outliers">Use visualizations such as box plots to identify outliers</a></li>
  <li><a href="#missing-data-patterns-mechanism-and-handling" id="toc-missing-data-patterns-mechanism-and-handling" class="nav-link" data-scroll-target="#missing-data-patterns-mechanism-and-handling">Missing Data: Patterns, Mechanism, and Handling</a></li>
  <li><a href="#linear-model---3-step-process" id="toc-linear-model---3-step-process" class="nav-link" data-scroll-target="#linear-model---3-step-process">Linear Model - 3 step process</a></li>
  <li><a href="#example-writeup" id="toc-example-writeup" class="nav-link" data-scroll-target="#example-writeup">Example Writeup</a></li>
  </ul></li>
  <li><a href="#define-semi-partial-correlations" id="toc-define-semi-partial-correlations" class="nav-link" data-scroll-target="#define-semi-partial-correlations">Define: Semi-partial Correlations</a>
  <ul class="collapse">
  <li><a href="#hypotheses-1" id="toc-hypotheses-1" class="nav-link" data-scroll-target="#hypotheses-1">Hypotheses</a></li>
  <li><a href="#technique" id="toc-technique" class="nav-link" data-scroll-target="#technique">Technique</a></li>
  </ul></li>
  <li><a href="#example-semi-partial-correlation-with-complete-data" id="toc-example-semi-partial-correlation-with-complete-data" class="nav-link" data-scroll-target="#example-semi-partial-correlation-with-complete-data">Example Semi-Partial Correlation with Complete Data</a>
  <ul class="collapse">
  <li><a href="#write-up" id="toc-write-up" class="nav-link" data-scroll-target="#write-up">Write up</a></li>
  </ul></li>
  <li><a href="#extra-code" id="toc-extra-code" class="nav-link" data-scroll-target="#extra-code">Extra Code:</a>
  <ul class="collapse">
  <li><a href="#partial-correlation-with-no-missing-data" id="toc-partial-correlation-with-no-missing-data" class="nav-link" data-scroll-target="#partial-correlation-with-no-missing-data">Partial Correlation with no Missing Data</a></li>
  <li><a href="#semi-partial-correlation-with-imputed-data" id="toc-semi-partial-correlation-with-imputed-data" class="nav-link" data-scroll-target="#semi-partial-correlation-with-imputed-data">Semi Partial Correlation with Imputed data</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Partial and Semi Partial Correlations</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Netasha K. Pizano </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>In this weeks lab, we are going to review Pearson’s partial and semi-partial correlations using simulated data inspired from a teacher-burnout study conducted by <span class="citation" data-cites="saloviita2021">Saloviita and Pakarinen (<a href="#ref-saloviita2021" role="doc-biblioref">2021</a>)</span>. Using partial and semi partial correlations we will investigate the relationship between the number of teacher call outs related to class size, while also taking into consideration or controlling for the number of years of classroom experience. Prior to conducting these techniques, we are going to review how we can handle missing data and identify and deal with outliers.</p>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) <span class="co">#use this package to create venn diagram </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(grid) <span class="co">#use this package to create venn diagram </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="co">#use this package with ggplot to create graphs and summarize data </span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="co">#use this package for creating multivariate normal distributions of variables </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr) <span class="co">#use this package for reading in the data that had a csv extension</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych) <span class="co">#use this package for describe function one of my favorites for descriptive statistics. </span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork) <span class="co">#use this package to print images side by side using a + symbol - so handy!</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MissMech) <span class="co">#use this package to run a Hawkin's test for MCAR, where normality is not assumed"</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(naniar) <span class="co">#use this package to identify and visualization missing data </span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mice) <span class="co">#use this package to create imputed data sets </span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co">#use this package for cleaning data, using pipes %&gt;%, so many packages and functions in one library &lt;3</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rstatix) <span class="co">#use this package to run boxplots and identify outliers</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="define-partial-correlations-goal" class="level2">
<h2 class="anchored" data-anchor-id="define-partial-correlations-goal">Define: Partial Correlations Goal</h2>
<p>Goal: Determine the relationship between two continuous variables after accounting for the influence of a continuous third variable, sometimes referred to as a extraneous factor.</p>
<ul>
<li>Partial correlation is the contribution of a predictor after the contributions of the other predictors have been taken out of both that predictor and the DV (Dong, Week 9).</li>
</ul>
<p>We are going to control for the number of years of teacher experience, a confounding variable while evaluating the relationship between teacher call outs and class size.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Partial-and-Semi-Partial-Correlations_files/figure-html/Venn%20Diagram-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="hypotheses" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses">Hypotheses</h3>
<p>HO: <span class="math inline">\(\rho_{yx.c}= 0\)</span>; The relationship between the number of teacher call outs and total number of students are not related after considering the influence of the number years of experience.</p>
<p>HA: <span class="math inline">\(\rho_{yx.c} \neq 0\)</span>; The relationship between the number of teacher call outs and total number of students are related after considering the influence of the number of years of teacher experience</p>
</section>
<section id="assumptions-of-pearson-correlation" class="level3">
<h3 class="anchored" data-anchor-id="assumptions-of-pearson-correlation">Assumptions of Pearson Correlation</h3>
<ul>
<li>Linearity
<ul>
<li>The relationship between pairs of of variables goes in one direction, monotones. There is an absence of a curve linear relationship.</li>
<li>Use scatterplots to evalaute the assumption of linearity.</li>
</ul></li>
<li>Independence
<ul>
<li>Observation responses are independent of one another. Data are not repeated measures from the same individual.</li>
<li>Make sure you understand how the data were collected.</li>
</ul></li>
<li>Normality
<ul>
<li>The distribution of variables are normally distributed.</li>
<li>Use histograms and QQ-plots to evaluate the normality assumption.</li>
</ul></li>
<li>No Outliers
<ul>
<li>Extreme responses could influence Pearson correlation coefficient-identify and remove them.</li>
<li>Using plots, identify extreme data points.</li>
</ul></li>
</ul>
</section>
<section id="technique-using-linear-model-regession-residuals" class="level3">
<h3 class="anchored" data-anchor-id="technique-using-linear-model-regession-residuals">Technique using Linear Model Regession Residuals</h3>
<p>A partial correlation can be obtain by correlating the residuals of the main variable and all other main variables after controlling for the extraneous variable.</p>
<ul>
<li><p>Residuals: whatever variance that is remaining or unexplained after predicting an outcome from some variable. Residuals are the differences between the regression line and the actual data. Residuals are the portion of teacher call-outs that remains unexplained after accounting for years of experience.</p></li>
<li><p>We need to standardize the data set in order to interpret the coefficients as effects. Again, standardized regression coefficients are equal to partial correlation because correlation is covariance on standardized data.</p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Partial-and-Semi-Partial-Correlations_files/figure-html/figures-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Partial-and-Semi-Partial-Correlations_files/figure-html/figures-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="example-partial-correlation-with-missing-data" class="level2">
<h2 class="anchored" data-anchor-id="example-partial-correlation-with-missing-data">Example Partial Correlation with Missing Data</h2>
<section id="read-in-the-data" class="level3">
<h3 class="anchored" data-anchor-id="read-in-the-data">Read in the data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read in the data using the read_csv</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>T_df_missing <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"missing_teacher_data.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>teacher_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"complete_teacher_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="wrangle-the-data-descriptive-statistics" class="level3">
<h3 class="anchored" data-anchor-id="wrangle-the-data-descriptive-statistics">Wrangle the data (descriptive statistics)</h3>
<p>The process of cleaning data is also known as data wrangling. During this part of the data analysis process we conduct procedures to “tidy” our data - every column is variable and every row is an observation. You should address issues such as invalid values, missing data, and data format issues.</p>
<p>- Describe the data using the describe function in the psych package to calculate basic statistics mean, median, etc., and find invalid values, missing data, and any format issues.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use the describe function in the psych package an output will provide the sample size, mean, standard deviation, median, trimmed mean, mean absolute deviation (mad), min, max, range, skewness, kurtosis, and standard error (se)</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">describe</span>(T_df_missing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           vars    n    mean      sd  median trimmed     mad   min     max
...1          1 4567 2284.00 1318.52 2284.00 2284.00 1693.13  1.00 4567.00
call_out      2 4567   29.99    0.99   29.99   29.99    1.01 26.48   33.29
class_size    3 4567   23.00    1.00   22.99   23.00    0.99 19.16   26.19
experience    4 4339   14.01    1.00   14.02   14.01    1.00 10.27   18.55
             range  skew kurtosis    se
...1       4566.00  0.00    -1.20 19.51
call_out      6.81  0.00    -0.03  0.01
class_size    7.03 -0.04     0.01  0.01
experience    8.28 -0.05     0.06  0.02</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#renaming the first column with id</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>T_df_missing <span class="ot">&lt;-</span> T_df_missing <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">id =</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="use-visualizations-such-as-box-plots-to-identify-outliers" class="level3">
<h3 class="anchored" data-anchor-id="use-visualizations-such-as-box-plots-to-identify-outliers">Use visualizations such as box plots to identify outliers</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use boxplot in ggplots to help identify outliers within the distribution of scores for call outs </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>T_df_missing <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> call_out)) <span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Partial-and-Semi-Partial-Correlations_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use boxplot in ggplot to help identify outliers within the distribution of class size</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>T_df_missing <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> class_size)) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Partial-and-Semi-Partial-Correlations_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use boxplot in ggplots to help identify outliers within the distribution of scores for experience</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>T_df_missing <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> experience)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 228 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Partial-and-Semi-Partial-Correlations_files/figure-html/unnamed-chunk-1-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#identify the values that may be considered outliers</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Identify outliers using the rstatix</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>outliers_callout<span class="ot">&lt;-</span> T_df_missing <span class="sc">%&gt;%</span> <span class="fu">identify_outliers</span>(call_out)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Print case numbers (using the original 'id' or row index)</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(outliers_callout<span class="sc">$</span>id)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  164  456  616 1011 1012 1126 1324 1622 1703 1911 1950 2135 2367 2383 2618
[16] 2697 2982 2983 3066 3245 3288 3429 3976 4088 4264 4376 4405 4526</code></pre>
</div>
</div>
</section>
<section id="missing-data-patterns-mechanism-and-handling" class="level3">
<h3 class="anchored" data-anchor-id="missing-data-patterns-mechanism-and-handling">Missing Data: Patterns, Mechanism, and Handling</h3>
<ul>
<li><p>Use the Hawkins test in the MissMech package to identify missing data patterns and determine the mechanism of missing data. “Missing data mechanisms or processes describe different ways in which the probability of missing values relates to the data: missing completely at random (MCAR), missing at random (MAR), and missing not at random (MNAR). <span class="citation" data-cites="enders2022">(<a href="#ref-enders2022" role="doc-biblioref">Craig K. Enders 2022</a>)</span>”</p></li>
<li><p>The techniques we use to handle missing data are dependent on the missing data mechanisms. Most assume that the data are missing at random (MAR).</p></li>
<li><p>MAR: MAR suggests that the probability of a missing value on variable x is unrelated to the values of x itself <span class="citation" data-cites="enders2006">(<a href="#ref-enders2006" role="doc-biblioref">Craig K. Enders 2006</a>)</span>. The missing data are related to some variable under investigation, but not the variable that the missing data came from.</p></li>
<li><p>MCAR: MCAR is a more stringent mechanism. MCAR suggests that the probability of missing a value on x is unrelated to any variable. The missing data are haphazardly missing.</p></li>
<li><p>MNAR: MNAR suggests that the missing data are related to the variable itself or the scores themselves.</p></li>
<li><p>The TestMCARNormality function will automatically group data by missingness patterns, imputes values, and compares covariances. A Hawkins test statistic <span class="math inline">\(p\)</span>-value will be reported. If the <span class="math inline">\(p\)</span>-value is greater than .05 than we fail to reject that the missing data are missing completely at random and a <span class="math inline">\(p\)</span>-value less than .05, suggest that we reject that the data are missing completely at random.</p></li>
</ul>
<p><img src="Figure/Missing%20Data%20Mechanism.png" class="img-fluid"></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use the TestMCARNormality to test if the missing data are missing completely at random. </span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>(MCARTest  <span class="ot">&lt;-</span> <span class="fu">TestMCARNormality</span>(T_df_missing))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
TestMCARNormality(data = T_df_missing)

Number of Patterns:  2 

Total number of cases used in the analysis:  4567 

 Pattern(s) used:
          id   call_out   class_size   experience   Number of cases
group.1    1          1            1            1              4339
group.2    1          1            1           NA               228

    Test of normality and Homoscedasticity:
  -------------------------------------------

Hawkins Test:

    P-value for the Hawkins test of normality and homoscedasticity:  2.224091e-14 

    Either the test of multivariate normality or homoscedasticity (or both) is rejected.
    Provided that normality can be assumed, the hypothesis of MCAR is 
    rejected at 0.05 significance level. 

Non-Parametric Test:

    P-value for the non-parametric test of homoscedasticity:  0.2239764 

    Reject Normality at 0.05 significance level.
    There is not sufficient evidence to reject MCAR at 0.05 significance level.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Use the miss_var_summary function to determine the proportion of missing data. </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">miss_var_summary</span>(T_df_missing)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  variable   n_miss pct_miss
  &lt;chr&gt;       &lt;int&gt;    &lt;num&gt;
1 experience    228     4.99
2 id              0     0   
3 call_out        0     0   
4 class_size      0     0   </code></pre>
</div>
</div>
<ul>
<li><p>The results from our Hawkin’s test suggest that there are two patterns, complete and missing data on the years of experience.</p></li>
<li><p>P-value for the Hawkins test is <span class="math inline">\(p \lt .05\)</span>. Therefore, we reject the null, which suggests that the missing data are missing completely at random (MCAR). Specially, approximately 5% of data are missing in teacher’s recorded years of experience.</p></li>
</ul>
<p>_ We are going to use the imputation method and assume that the data are MAR. We are going to use the mice package to impute the data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Remove the first column of the data frame because in the next step we are going to impute.</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>T_df_missing<span class="ot">&lt;-</span> T_df_missing[<span class="sc">-</span>(<span class="dv">1</span>)]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co">#list the data set name, m = to the number of imputed data sets, method = predictive mean matching, and seed = any value.</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>imputed_teacher_data <span class="ot">&lt;-</span> <span class="fu">mice</span>(T_df_missing, <span class="at">m =</span> <span class="dv">50</span>, <span class="at">method =</span> <span class="st">"pmm"</span>, <span class="at">seed =</span> <span class="dv">123</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="linear-model---3-step-process" class="level3">
<h3 class="anchored" data-anchor-id="linear-model---3-step-process">Linear Model - 3 step process</h3>
<ul>
<li>When we don’t have deal with imputed data sets follow these steps</li>
<li>Step 0: Standardize the data, we want everything to be on the same scale</li>
<li>Step 1: Use the linear model function to predict the outcome from the extraneous variable.</li>
<li>Step 1.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</li>
<li>Step 2: Use a linear model function again to predict the main explanatory variable, but from the second extraneous variable.</li>
<li>Step 2.2: Collect the residuals; the portion or variance in the in the main explanatory variable that is not explained after the regression.</li>
<li>Step 3: Use the corr Function to relate whatever variance that is left in class size and callout.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Because we are dealing with missing data we can create a function that can loop through </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>partial_list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span>imputed_teacher_data<span class="sc">$</span>m, <span class="cf">function</span>(i) {</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#pull all 50 imputed data sets and assign them to data using the complete function </span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  data <span class="ot">&lt;-</span> <span class="fu">complete</span>(imputed_teacher_data, i)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="co">#then scale each variable  across all 50 datasets </span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>  Impute_Std_T_df<span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(call_out, class_size, experience),</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>                  <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">scale</span>(.))))</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  model_CO <span class="ot">&lt;-</span> <span class="fu">lm</span>(call_out <span class="sc">~</span> experience, <span class="at">data =</span> Impute_Std_T_df)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 1.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>res_CO <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_CO)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Use a linear model function again to predict the same outcome, but the second explanatory variable. </span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>model_CS <span class="ot">&lt;-</span> <span class="fu">lm</span>(class_size <span class="sc">~</span> experience, <span class="at">data =</span> Impute_Std_T_df)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 2.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>res_CS <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_CS)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 3: Use the corr Function to relate whatever variance that is left in class size and callout</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a> <span class="fu">cor</span>(res_CO, res_CS)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 4: we have to use fisher transformation to pool each of the 50 data set because correlations are bounded between -1 and 1 and their distribution will be skewed towards those boundaries.  </span></span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>z_vals <span class="ot">&lt;-</span> <span class="fu">atanh</span>(<span class="fu">unlist</span>(partial_list))</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 5: we have to find the means of the z-values. Averaging is part of the "pooling process"</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>z_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(z_vals)</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 6: Find the variance within, between, and total the imputations to get standard errors</span></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Within-imputation variance</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>W <span class="ot">&lt;-</span> <span class="fu">mean</span>((z_vals <span class="sc">-</span> z_bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Between-imputation variance</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>B <span class="ot">&lt;-</span> <span class="fu">var</span>(z_vals)</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Total variance</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>T_var <span class="ot">&lt;-</span> W <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span><span class="sc">/</span>imputed_teacher_data<span class="sc">$</span>m) <span class="sc">*</span> B</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Standard error</span></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(T_var)</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 7: convert back to the correlation because we modified them in the previous step </span></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>pooled_r <span class="ot">&lt;-</span> <span class="fu">tanh</span>(z_bar)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 8: Calculate confidence intervals </span></span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> <span class="fu">tanh</span>(z_bar <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se)</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> <span class="fu">tanh</span>(z_bar <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se)</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 7, let's print the final correlation</span></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>(<span class="fu">c</span>(<span class="at">lower =</span> lower, <span class="at">estimate =</span> pooled_r, <span class="at">upper =</span> upper))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    lower  estimate     upper 
0.8578654 0.8594057 0.8609306 </code></pre>
</div>
</div>
<p>Note: We can see that the correlation from the imputed data set is close to the data set with complete data.</p>
</section>
<section id="example-writeup" class="level3">
<h3 class="anchored" data-anchor-id="example-writeup">Example Writeup</h3>
<p>A partial correlation analysis was conducted to examine the relationship between teacher call-outs and class size, while controlling for years of experience. After controlling for years of experience, the partial correlation was positive, strong, and statistically significant (𝑟 = 0.86, 95% CI [0.85, 0.86]). This suggests that even when a teacher has years of experience, the toll of class size is significantly related to the number of class outs.</p>
</section>
</section>
<section id="define-semi-partial-correlations" class="level2">
<h2 class="anchored" data-anchor-id="define-semi-partial-correlations">Define: Semi-partial Correlations</h2>
<ul>
<li>Similar to partial correlation, semi-partial correlation aims to remove the influence of the third variable but only in one variable. Semi partial correlations provide the unique contribution of the explanatory variable to the outcome. Remove the influence of a teacher’s years of experience from class size only. In other words, the number of call out is explained by whatever variance is left in class size after controlling for the number of years of teacher experience.</li>
</ul>
<section id="hypotheses-1" class="level3">
<h3 class="anchored" data-anchor-id="hypotheses-1">Hypotheses</h3>
<p>HO: <span class="math inline">\(\rho_{y.xc}= 0\)</span>; The total number of students does not uniquely relate or predict the number of teacher call outs.</p>
<p>HA: <span class="math inline">\(\rho_{yx.c} \neq 0\)</span>; The total number of students uniquely relates to the number of teacher call outs.</p>
<ul>
<li>We are not evaluating the relation between teacher call outs and class size while controlling for the number years of experience.</li>
</ul>
</section>
<section id="technique" class="level3">
<h3 class="anchored" data-anchor-id="technique">Technique</h3>
<p>A semi partial correlation can be obtain by using a linear model that regresses the either the outcome or the primary explanatory variable from the third variable, the extraneous variable. The third variable only influences one of the variables. Then,correlating the residuals from the first model with the outcome.</p>
<ul>
<li><p>You could also run one additive regression model that includes all explanatory variables related to the outcome and simply evaluate the t-statistic. The t-value tests whether class size uniquely explains the number of teacher call outs.</p></li>
<li><p>Step 1: Use the linear model function to test the unique relation between the explanatory variable and the third variable</p></li>
<li><p>Step 1.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</p></li>
<li><p>Step 2: Correlate the remain residual in the primary explantory variable with the outcome.</p></li>
<li><p>We test the null hypothesis using a test statistic that follows an approximate t-distribution. After calculating a semi partial correlation estimate, we use an approximate t-distribution test statistic to determine if the partial correlation is statistically significant.</p></li>
</ul>
</section>
</section>
<section id="example-semi-partial-correlation-with-complete-data" class="level2">
<h2 class="anchored" data-anchor-id="example-semi-partial-correlation-with-complete-data">Example Semi-Partial Correlation with Complete Data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># When we don't have deal with imputed data sets follow these steps </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the data, we want everything to be on the same scale </span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation is simply the standardized regression </span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>semi_teacher_data<span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"complete_teacher_data.csv"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># We have to remove the firset column with Ids</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>semi_teacher_data<span class="ot">&lt;-</span> semi_teacher_data[<span class="sc">-</span>(<span class="dv">1</span>)]</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># We are going to scale the dataset</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>semi_teacher_data<span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(semi_teacher_data))</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Use the linear model function to test the unique relation between the explanatory variable and the third variable </span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>model_CS <span class="ot">&lt;-</span> <span class="fu">lm</span>(class_size <span class="sc">~</span> experience, <span class="at">data =</span> semi_teacher_data)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 1.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>res_CS <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_CS)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 2: Use the corr Function to relate whatever variance that is left in class size to </span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a> (semi_cor<span class="ot">&lt;-</span> <span class="fu">cor.test</span>(semi_teacher_data<span class="sc">$</span>call_out, res_CS))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  semi_teacher_data$call_out and res_CS
t = 94.924, df = 4565, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.8047109 0.8242276
sample estimates:
      cor 
0.8146998 </code></pre>
</div>
</div>
<section id="write-up" class="level3">
<h3 class="anchored" data-anchor-id="write-up">Write up</h3>
<p>To assess the unique contribution of class size to call-out behavior, a semi-partial correlation was computed accounting for teachers’ years of experience. The semi-partial correlation between class size and call-out behavior was (r = .81, t = 94.92(df = 4565), p <span class="math inline">\(\lt\)</span>.05, 95% CI [0.80, 0.82]), indicating that class size explained approximately 64% of the variance in call-out behavior beyond the variance shared with teaching experience.</p>
</section>
</section>
<section id="extra-code" class="level2">
<h2 class="anchored" data-anchor-id="extra-code">Extra Code:</h2>
<section id="partial-correlation-with-no-missing-data" class="level3">
<h3 class="anchored" data-anchor-id="partial-correlation-with-no-missing-data">Partial Correlation with no Missing Data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># When we don't have deal with imputed data sets follow these steps </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the data, we want everything to be on the same scale </span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation is simply the standardized regression </span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>teacher_data<span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">scale</span>(teacher_data))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Use the linear model function to predict the outcome from one explanatory (independent,I.V., etc.) variable. Any explanatory variable can come first, but only model one!</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>model_CO <span class="ot">&lt;-</span> <span class="fu">lm</span>(call_out <span class="sc">~</span> experience, <span class="at">data =</span> teacher_data)</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 1.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>res_CO <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_CO)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 2: Use a linear model function again to predict the same outcome, but the second explanatory variable. </span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>model_CS <span class="ot">&lt;-</span> <span class="fu">lm</span>(class_size <span class="sc">~</span> experience, <span class="at">data =</span> teacher_data)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 2.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>res_CS <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_CS)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3: Use the corr Function to relate whatever variance that is left in class size and callout </span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>partial_cor <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(res_CO, res_CS)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>partial_cor</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  res_CO and res_CS
t = 114.12, df = 4565, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.8527709 0.8678363
sample estimates:
      cor 
0.8604916 </code></pre>
</div>
</div>
</section>
<section id="semi-partial-correlation-with-imputed-data" class="level3">
<h3 class="anchored" data-anchor-id="semi-partial-correlation-with-imputed-data">Semi Partial Correlation with Imputed data</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Because we are dealing with missing data we can create a function that can loop through </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>semi_partial_list <span class="ot">&lt;-</span> <span class="fu">lapply</span>(<span class="dv">1</span><span class="sc">:</span>imputed_teacher_data<span class="sc">$</span>m, <span class="cf">function</span>(i) {</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#pull all 50 imputed data sets and assign them to data using the complete function </span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  semi_data <span class="ot">&lt;-</span> <span class="fu">complete</span>(imputed_teacher_data, i)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#then scale each variable  across all 50 datasets </span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  semi_impute_std_T_df<span class="ot">&lt;-</span> semi_data <span class="sc">%&gt;%</span> </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">c</span>(call_out, class_size, experience),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">as.numeric</span>(<span class="fu">scale</span>(.))))</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 1: Use a linear model function to predict the explanatory variable from the third extraneous variable</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>model_CS <span class="ot">&lt;-</span> <span class="fu">lm</span>(class_size <span class="sc">~</span> experience, <span class="at">data =</span> semi_impute_std_T_df)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co">#Step 1.2: Collect the residuals; the portion or variance in the outcome that is not explained after the regression</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>res_CS <span class="ot">&lt;-</span> <span class="fu">resid</span>(model_CS)</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 2: Use the corr Function to relate whatever variance that is left in class size to </span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a> semi_cor<span class="ot">&lt;-</span> <span class="fu">cor</span>(semi_impute_std_T_df<span class="sc">$</span>call_out, res_CS)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert list to numeric vector</span></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a>semi_partial_vec <span class="ot">&lt;-</span> <span class="fu">unlist</span>(semi_partial_list)</span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-23"><a href="#cb23-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Fisher z transform</span></span>
<span id="cb23-24"><a href="#cb23-24" aria-hidden="true" tabindex="-1"></a>z_vals <span class="ot">&lt;-</span> <span class="fu">atanh</span>(semi_partial_vec)</span>
<span id="cb23-25"><a href="#cb23-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-26"><a href="#cb23-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Pool Fisher z values</span></span>
<span id="cb23-27"><a href="#cb23-27" aria-hidden="true" tabindex="-1"></a>z_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(z_vals)</span>
<span id="cb23-28"><a href="#cb23-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-29"><a href="#cb23-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Back-transform to correlation</span></span>
<span id="cb23-30"><a href="#cb23-30" aria-hidden="true" tabindex="-1"></a>pooled_semi_cor <span class="ot">&lt;-</span> <span class="fu">tanh</span>(z_bar)</span>
<span id="cb23-31"><a href="#cb23-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-32"><a href="#cb23-32" aria-hidden="true" tabindex="-1"></a>pooled_semi_cor</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8137159</code></pre>
</div>
</div>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-enders2022" class="csl-entry" role="listitem">
Enders, Craig K. 2022. <em>Applied Missing Data Analysis</em>. Second. New York: Guildford Press.
</div>
<div id="ref-enders2006" class="csl-entry" role="listitem">
Enders, Craig K. 2006. <span>“A Primer on the Use of Modern Missing-Data Methods in Psychosomatic Medicine Research.”</span> <em>Psychosomatic Medicine</em> 68 (3): 427–36. <a href="https://doi.org/10.1097/01.psy.0000221275.75056.d8">https://doi.org/10.1097/01.psy.0000221275.75056.d8</a>.
</div>
<div id="ref-saloviita2021" class="csl-entry" role="listitem">
Saloviita, Timo, and Eija Pakarinen. 2021. <span>“Teacher Burnout Explained: Teacher-, Student-, and Organisation-Level Variables.”</span> <em>Teaching and Teacher Education</em> 97 (January): 103221. <a href="https://doi.org/10.1016/j.tate.2020.103221">https://doi.org/10.1016/j.tate.2020.103221</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>